name: Check Vulnerabilities

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-vulnerabilities:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'  

    - name: Restore dependencies
      run: dotnet restore

    - name: List vulnerable packages
      run: dotnet list package --vulnerable
        if [ $? -ne 0 ]; then
          echo "Vulnerabilities found!"
          exit 1
        fi
