name: Check Vulnerabilities

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-vulnerabilities:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'  

    - name: Restore dependencies
      working-directory: ./Exercise_31a
      run: dotnet restore

    - name: List vulnerable packages
      working-directory: ./Exercise_31a
      run: |
        vulnerable_packages=$(dotnet list package --vulnerable)
        echo "$vulnerable_packages"
        if [[ "$vulnerable_packages" != *"No vulnerable packages found"* ]]; then
          echo "Vulnerabilities found!"
          exit 1
        fi
