version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/Exercise_03a"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/Exercise_03b"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/Exercise_03c"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/Exercise_03d"
    schedule:
      interval: "weekly"
