name: Check Vulnerabilities

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-vulnerabilities:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'  

    - name: Restore dependencies for Exercise_13b
      working-directory: ./Exercise_13b
      run: dotnet restore

    - name: List vulnerable packages for Exercise_13b
      working-directory: ./Exercise_13b
      run: |
        # Capture the output of the command into a variable
        output=$(dotnet list package --vulnerable)
        
        # Output the result to the GitHub Actions logs
        echo "$output"
        
        # Check if any vulnerabilities were found
        if [[ "$output" == *"has the following vulnerable packages"* ]]; then
          echo "Vulnerabilities found!"
          exit 1  # Fail the workflow
        else
          echo "No vulnerabilities found."
        fi

    - name: Restore dependencies for Exercise_31a
      working-directory: ./Exercise_31a
      run: dotnet restore

    - name: List vulnerable packages for Exercise_31a
      working-directory: ./Exercise_31a
      run: |
        # Capture the output of the command into a variable
        output=$(dotnet list package --vulnerable)
        
        # Output the result to the GitHub Actions logs
        echo "$output"
        
        # Check if any vulnerabilities were found
        if [[ "$output" == *"has the following vulnerable packages"* ]]; then
          echo "Vulnerabilities found!"
          exit 1  # Fail the workflow
        else
          echo "No vulnerabilities found."
        fi
